/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class emulin_device_NativeConsole */

#ifndef _Included_emulin_device_NativeConsole
#define _Included_emulin_device_NativeConsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1read
  (JNIEnv *, jclass);

/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_set_parameter
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1set_1parameter
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_israw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1israw
  (JNIEnv *, jobject);

/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_check_int
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1check_1int
  (JNIEnv *, jobject);

/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_cancel_int
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1cancel_1int
  (JNIEnv *, jobject);

/*
 * Class:     emulin_device_NativeConsole
 * Method:    native_set_int
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_emulin_device_NativeConsole_native_1set_1int
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
