// ----------------------------------------
//  Allocation-free AArch64 decode result (issue #951 Phase 1)
// ----------------------------------------
package emulin;

final class Aarch64DecodedInsn {
  enum Operation {
    MOVN, MOVZ, MOVK,
    ADR, ADRP,
    ADD_IMMEDIATE, ADDS_IMMEDIATE, SUB_IMMEDIATE, SUBS_IMMEDIATE,
    ADD_SHIFTED_REGISTER, ADDS_SHIFTED_REGISTER,
    SUB_SHIFTED_REGISTER, SUBS_SHIFTED_REGISTER,
    ADD_EXTENDED_REGISTER, ADDS_EXTENDED_REGISTER,
    SUB_EXTENDED_REGISTER, SUBS_EXTENDED_REGISTER,
    AND_IMMEDIATE, ORR_IMMEDIATE, EOR_IMMEDIATE, ANDS_IMMEDIATE,
    AND_SHIFTED_REGISTER, BIC_SHIFTED_REGISTER,
    ORR_SHIFTED_REGISTER, ORN_SHIFTED_REGISTER,
    EOR_SHIFTED_REGISTER, EON_SHIFTED_REGISTER,
    ANDS_SHIFTED_REGISTER, BICS_SHIFTED_REGISTER,
    SBFM, BFM, UBFM, EXTR,
    MADD, MSUB, UMADDL, UMSUBL, SMADDL, SMSUBL, UMULH, SMULH, UDIV, SDIV,
    RBIT, REV16, REV32, REV64, CLZ, CLS, CRC32,
    LSL_VARIABLE, LSR_VARIABLE, ASR_VARIABLE, ROR_VARIABLE,
    CSEL, CSINC, CSINV, CSNEG,
    CCMP_IMMEDIATE, CCMP_REGISTER, CCMN_IMMEDIATE, CCMN_REGISTER,
    B, BL, B_COND, CBZ, CBNZ, TBZ, TBNZ, BR, BLR, RET,
    STR, LDR, LDR_SIGNED, STP, LDP, LDP_SIGNED,
    LDR_LITERAL, LDR_SIGNED_LITERAL,
    DUP_VECTOR_BYTE, DUP_VECTOR_D_LANE,
    LD1_VECTOR_16B, LD1_VECTOR_2_16B, LD1_VECTOR_D_LANE, LD1R_VECTOR_2D,
    CMEQ_VECTOR_BYTE, CMEQ_VECTOR_BYTE_ZERO,
    AND_VECTOR, ORR_VECTOR, BIT_VECTOR, EOR_VECTOR,
    BIC_VECTOR_IMMEDIATE_HALFWORD, UMAXP_VECTOR_BYTE,
    UMINP_VECTOR_BYTE, ADDP_VECTOR_BYTE, EXT_VECTOR_16B, CMHS_VECTOR_BYTE,
    ADD_VECTOR_2D, SADDW_VECTOR_2D,
    SADDW_VECTOR_4S, SADDW2_VECTOR_4S,
    UADDW_VECTOR_4S, UADDW2_VECTOR_4S,
    ADDV_VECTOR_4S,
    REV32_VECTOR_16B,
    ZIP1_VECTOR_16B, ZIP2_VECTOR_16B,
    SXTL_VECTOR_8H, SXTL2_VECTOR_8H,
    SHRN_VECTOR_8B, ADDHN_VECTOR_8B, USHR_VECTOR_64, USHL_VECTOR_2D,
    UZP1_VECTOR,
    FMOV_GENERAL_FROM_D, FMOV_D_FROM_GENERAL,
    FMOV_GENERAL_FROM_S, FMOV_S_FROM_GENERAL, FMOV_VECTOR_64, FMOV_IMMEDIATE,
    FCMP_D_ZERO, FCMP_D_REGISTER,
    SCVTF_D_FROM_GENERAL, UCVTF_D_FROM_GENERAL,
    SCVTF_D_FROM_VECTOR, UCVTF_D_FROM_VECTOR,
    FCVT_D_FROM_S, FCVT_S_FROM_D,
    FCVTZS_GENERAL_FROM_FP, FCVTZU_GENERAL_FROM_FP,
    FCVTMS_GENERAL_FROM_FP, FCVTMU_GENERAL_FROM_FP,
    FADD_D, FSUB_D, FMUL_D, FDIV_D, FRINTM_D,
    MOVE_VECTOR_D_LANE, MOVE_VECTOR_FROM_GENERAL_LANE,
    MOVE_GENERAL_FROM_VECTOR_LANE,
    STR_VECTOR_32, LDR_VECTOR_32, STR_VECTOR_64, LDR_VECTOR_64,
    STR_VECTOR_128, LDR_VECTOR_128,
    STP_VECTOR_64, LDP_VECTOR_64, STP_VECTOR_128, LDP_VECTOR_128, MOVI_VECTOR,
    MRS_DCZID_EL0, MRS_TPIDR_EL0, MSR_TPIDR_EL0,
    LOAD_EXCLUSIVE, STORE_EXCLUSIVE, LOAD_ACQUIRE, STORE_RELEASE,
    MEMORY_BARRIER, NOP, SVC
  }

  enum ShiftType { NONE, LSL, LSR, ASR, ROR }
  enum ExtendType { NONE, UXTB, UXTH, UXTW, UXTX, SXTB, SXTH, SXTW, SXTX }
  enum AddressMode { NONE, OFFSET, PRE_INDEX, POST_INDEX, LITERAL }

  Operation operation;
  int raw;
  int dataSize;
  int accessSize;
  int rd;
  int rn;
  int rm;
  int ra;
  int rt2;
  long immediate;
  int immr;
  int imms;
  ShiftType shiftType;
  ExtendType extendType;
  int shiftAmount;
  AddressMode addressMode;
  int condition;
  int bitIndex;
  boolean setsFlags;

  void reset( int instruction ) {
    raw = instruction;
    operation = null;
    dataSize = 0;
    accessSize = 0;
    rd = rn = rm = ra = rt2 = -1;
    immediate = 0;
    immr = imms = -1;
    shiftType = ShiftType.NONE;
    extendType = ExtendType.NONE;
    shiftAmount = 0;
    addressMode = AddressMode.NONE;
    condition = -1;
    bitIndex = -1;
    setsFlags = false;
  }
}
