// ----------------------------------------
//  Linux AArch64 syscall number table (asm-generic ABI, issue #951)
// ----------------------------------------
package emulin;

final class Aarch64SyscallTable {
  static final int SYS_GETCWD = 17;
  static final int SYS_DUP = 23;
  static final int SYS_FCNTL = 25;
  static final int SYS_IOCTL = 29;
  static final int SYS_MKDIRAT = 34;
  static final int SYS_UNLINKAT = 35;
  static final int SYS_SYMLINKAT = 36;
  static final int SYS_LINKAT = 37;
  static final int SYS_RENAMEAT = 38;
  static final int SYS_STATFS = 43;
  static final int SYS_FSTATFS = 44;
  static final int SYS_TRUNCATE = 45;
  static final int SYS_FTRUNCATE = 46;
  static final int SYS_FACCESSAT = 48;
  static final int SYS_CHDIR = 49;
  static final int SYS_FCHMODAT = 53;
  static final int SYS_FCHOWNAT = 54;
  static final int SYS_OPENAT = 56;
  static final int SYS_CLOSE = 57;
  static final int SYS_GETDENTS64 = 61;
  static final int SYS_LSEEK = 62;
  static final int SYS_READ = 63;
  static final int SYS_WRITE = 64;
  static final int SYS_READV = 65;
  static final int SYS_WRITEV = 66;
  static final int SYS_READLINKAT = 78;
  static final int SYS_NEWFSTATAT = 79;
  static final int SYS_FSTAT = 80;
  static final int SYS_UTIMENSAT = 88;
  static final int SYS_EXIT = 93;
  static final int SYS_EXIT_GROUP = 94;
  static final int SYS_SET_TID_ADDRESS = 96;
  static final int SYS_FUTEX = 98;
  static final int SYS_SET_ROBUST_LIST = 99;
  static final int SYS_CLOCK_GETTIME = 113;
  static final int SYS_CLOCK_GETRES = 114;
  static final int SYS_SCHED_YIELD = 124;
  static final int SYS_KILL = 129;
  static final int SYS_TGKILL = 131;
  static final int SYS_RT_SIGACTION = 134;
  static final int SYS_RT_SIGPROCMASK = 135;
  static final int SYS_SETPGID = 154;
  static final int SYS_GETPGID = 155;
  static final int SYS_UNAME = 160;
  static final int SYS_GETRLIMIT = 163;
  static final int SYS_GETTIMEOFDAY = 169;
  static final int SYS_GETPID = 172;
  static final int SYS_GETPPID = 173;
  static final int SYS_GETUID = 174;
  static final int SYS_GETEUID = 175;
  static final int SYS_GETGID = 176;
  static final int SYS_GETEGID = 177;
  static final int SYS_GETTID = 178;
  static final int SYS_BRK = 214;
  static final int SYS_MUNMAP = 215;
  static final int SYS_CLONE = 220;
  static final int SYS_EXECVE = 221;
  static final int SYS_MMAP = 222;
  static final int SYS_MPROTECT = 226;
  static final int SYS_MADVISE = 233;
  static final int SYS_WAIT4 = 260;
  static final int SYS_PRLIMIT64 = 261;
  static final int SYS_RENAMEAT2 = 276;
  static final int SYS_GETRANDOM = 278;
  static final int SYS_RSEQ = 293;
  static final int SYS_FACCESSAT2 = 439;
  static final int SYS_FCHMODAT2 = 452;

  long dispatch( SyscallAarch64 syscall, int number, long x0, long x1, long x2,
                 long x3, long x4, long x5 ) {
    return switch( number ) {
      case SYS_GETCWD -> syscall.aarch64Getcwd( x0, x1 );
      case SYS_DUP -> syscall.sys_dup( x0, 0, 0, 0, 0 );
      case SYS_FCNTL -> syscall.sys_fcntl( x0, x1, x2, 0, 0 );
      case SYS_IOCTL -> syscall.aarch64Ioctl( x0, x1, x2 );
      case SYS_MKDIRAT -> syscall.aarch64Mkdirat( x0, x1, x2 );
      case SYS_UNLINKAT -> syscall.aarch64Unlinkat( x0, x1, x2 );
      case SYS_SYMLINKAT -> syscall.aarch64Symlinkat( x0, x1, x2 );
      case SYS_LINKAT -> syscall.aarch64Linkat( x0, x1, x2, x3, x4 );
      case SYS_RENAMEAT -> syscall.aarch64Renameat( x0, x1, x2, x3 );
      case SYS_STATFS -> syscall.aarch64Statfs( x0, x1 );
      case SYS_FSTATFS -> syscall.aarch64Fstatfs( x0, x1 );
      case SYS_TRUNCATE -> syscall.aarch64Truncate( x0, x1 );
      case SYS_FTRUNCATE -> syscall.sys_ftruncate( x0, x1, 0, 0, 0 );
      case SYS_FACCESSAT -> syscall.aarch64Faccessat( x0, x1, x2, 0, false );
      case SYS_CHDIR -> syscall.sys_chdir( x0, 0, 0, 0, 0 );
      case SYS_FCHMODAT -> syscall.aarch64Fchmodat( x0, x1, x2, 0 );
      case SYS_FCHOWNAT -> syscall.aarch64Fchownat( x0, x1, x2, x3, x4 );
      case SYS_OPENAT -> syscall.aarch64Openat( x0, x1, x2, x3 );
      case SYS_CLOSE -> syscall.sys_close( x0, 0, 0, 0, 0 );
      case SYS_GETDENTS64 -> syscall.sys_getdents64( x0, x1, x2 );
      case SYS_LSEEK -> syscall.sys_lseek( x0, x1, x2, 0, 0 );
      case SYS_READ -> syscall.aarch64Read( x0, x1, x2 );
      case SYS_WRITE -> syscall.aarch64Write( x0, x1, x2 );
      case SYS_READV -> syscall.aarch64Readv( x0, x1, x2 );
      case SYS_WRITEV -> syscall.aarch64Writev( x0, x1, x2 );
      case SYS_READLINKAT -> syscall.aarch64Readlinkat( x0, x1, x2, x3 );
      case SYS_NEWFSTATAT -> syscall.aarch64Newfstatat( x0, x1, x2, x3 );
      case SYS_FSTAT -> syscall.aarch64Fstat( x0, x1 );
      case SYS_UTIMENSAT -> syscall.aarch64Utimensat( x0, x1, x2, x3 );
      case SYS_EXIT -> syscall.aarch64Exit( x0, false );
      case SYS_EXIT_GROUP -> syscall.aarch64Exit( x0, true );
      case SYS_SET_TID_ADDRESS -> syscall.aarch64SetTidAddress( x0 );
      case SYS_FUTEX -> syscall.aarch64Futex( x0, x1, x2, x3, x4, x5 );
      case SYS_SET_ROBUST_LIST, SYS_RSEQ -> 0;
      case SYS_CLOCK_GETTIME -> syscall.aarch64ClockGettime( x0, x1 );
      case SYS_CLOCK_GETRES -> syscall.aarch64ClockGetres( x0, x1 );
      case SYS_SCHED_YIELD -> 0;
      case SYS_KILL -> syscall.aarch64Kill( x0, x1 );
      case SYS_TGKILL -> syscall.aarch64Tgkill( x0, x1, x2 );
      case SYS_RT_SIGACTION -> syscall.aarch64RtSigaction( x0, x1, x2, x3 );
      case SYS_RT_SIGPROCMASK -> syscall.aarch64RtSigprocmask( x0, x1, x2, x3 );
      case SYS_SETPGID -> syscall.aarch64Setpgid( x0, x1 );
      case SYS_GETPGID -> syscall.aarch64Getpgid( x0 );
      case SYS_UNAME -> syscall.sys_uname( x0, 0, 0, 0, 0 );
      case SYS_GETRLIMIT -> syscall.aarch64Prlimit64( 0, x0, 0, x1 );
      case SYS_GETTIMEOFDAY -> syscall.sys_gettimeofday( x0, x1, 0, 0, 0 );
      case SYS_GETPID -> syscall.sys_getpid( 0, 0, 0, 0, 0 );
      case SYS_GETPPID -> syscall.sys_getppid( 0, 0, 0, 0, 0 );
      case SYS_GETUID -> syscall.sys_getuid( 0, 0, 0, 0, 0 );
      case SYS_GETEUID -> syscall.sys_geteuid( 0, 0, 0, 0, 0 );
      case SYS_GETGID -> syscall.sys_getgid( 0, 0, 0, 0, 0 );
      case SYS_GETEGID -> syscall.sys_getegid( 0, 0, 0, 0, 0 );
      case SYS_GETTID -> syscall.aarch64Gettid();
      case SYS_BRK -> syscall.sys_brk( x0, 0, 0, 0, 0 );
      case SYS_MUNMAP -> syscall.sys_munmap( x0, x1, 0, 0, 0 );
      // AArch64 clone ABI: flags, stack, parent_tid, tls, child_tid.
      case SYS_CLONE -> syscall.aarch64Clone( x0, x1, x2, x3, x4 );
      case SYS_EXECVE -> syscall.aarch64Execve( x0, x1, x2 );
      case SYS_MMAP -> syscall.aarch64Mmap( x0, x1, x2, x3, x4, x5 );
      case SYS_MPROTECT -> syscall.sys_mprotect( x0, x1, x2, 0, 0 );
      case SYS_MADVISE -> syscall.aarch64Madvise( x0, x1, x2 );
      case SYS_WAIT4 -> syscall.aarch64Wait4( x0, x1, x2, x3 );
      case SYS_PRLIMIT64 -> syscall.aarch64Prlimit64( x0, x1, x2, x3 );
      case SYS_RENAMEAT2 -> syscall.aarch64Renameat2( x0, x1, x2, x3, x4 );
      case SYS_GETRANDOM -> syscall.aarch64Getrandom( x0, x1, x2 );
      case SYS_FACCESSAT2 -> syscall.aarch64Faccessat( x0, x1, x2, x3, true );
      case SYS_FCHMODAT2 -> syscall.aarch64Fchmodat( x0, x1, x2, x3 );
      default -> Syscall.ENOSYS;
    };
  }
}
